(cl:in-package #:common-lisp-user)

(defpackage #:cluster-risc-v-common
  (:use #:common-lisp)
  (:export
   #:+opcode-load+
   #:+func3-load-byte+
   #:+func3-load-half+
   #:+func3-load-word+
   #:+func3-load-double+
   #:+func3-load-byte-unsigned+
   #:+func3-load-half-unsigned+
   #:+func3-load-word-unsigned+
   #:+opcode-store+
   #:+func-3-store-byte
   #:+func-3-store-half
   #:+func-3-store-word
   #:+func-3-store-double
   #:+opcode-integer-register-register-double+
   #:+func-3-add+
   #:+func-7-add+
   #:+func-3-sub+
   #:+func-7-sub+
   #:+func-3-sll+
   #:+func-7-sll+
   #:+func-3-slt+
   #:+func-7-slt+
   #:+func-3-sltu+
   #:+func-7-sltu+
   #:+func-3-xor+
   #:+func-7-xor+
   #:+func-3-srl+
   #:+func-7-srl+
   #:+func-3-sra+
   #:+func-7-sra+
   #:+func-3-or+
   #:+func-7-or+
   #:+func-3-and+
   #:+func-7-and+
   #:+opcode-integer-register-register-word+
   #:+func-3-addw+
   #:+func-7-addw+
   #:+func-3-subw+
   #:+func-7-subw+
   #:+func-3-sllw+
   #:+func-7-sllw+
   #:+func-3-srlw+
   #:+func-7-srlw+
   #:+func-3-sraw+
   #:+func-7-sraw+
   #:+opcode-immediate-double+
   #:+func-3-addi+
   #:+func-3-slli+
   #:+func-3-slti+
   #:+func-3-sltiu+
   #:+func-3-xori+
   #:+func-3-srli+
   #:+func-3-srai+
   #:+func-3-ori+
   #:+func-3-andi+
   #:+opcode-immediate-word+
   #:+func-3-addiw+
   #:+func-3-slliw+
   #:+func-3-srliw+
   #:+func-3-sraiw+
   #:+opcode-branch+
   #:+func-3-beq+
   #:+func-3-bne+
   #:+func-3-blt+
   #:+func-3-bge+
   #:+func-3-bltu+
   #:+func-3-bgeu+
   #:+opcode-lui+
   #:+opcode-auipc+
   #:+opcode-jalr+
   #:+funct-3-jalr+
   #:+opcode-jal+))
